### ISSUE TITLE
ddl package files missing from zip

### ISSUE THREAD

**Issue by elewis33** [bcoulam/plsqlstarter#2]
Hi Bill, looks like the ddl_utils.pkb and ddl_utils.pks files are missing from the Simple.zip file. So if someone downloads the zip file (as I did) rather than cloning the repo then they don't get a complete package. 

I know, who downloads a zip file from Github, right? But it happened. Hope all is well with you. Miss seeing you at the UTOUG events.

**Comment by bcoulam** [comment]
Thanks Earl for bringing that to my attention. I've added those two missing files to Simple.zip.
While looking into this, I discovered there is a difference between ddl_utils package files in Simple and the Starter_12c folders. The latter has two extra routines, one to drop_job and the other to drop_sched, both of which use the 10g+ Oracle Scheduler features. I'll get them in sync here, shortly.

**Comment by bcoulam** [comment]
Brought the four copies of ddl_utils (Simple, Starter, Starter_12c and Simple.zip) in sync with one another. Tested they still compile on 11.2.0.4. Pushed to master.

**Comment by elewis33** [comment]
Thanks Bill.
